### ISSUE TITLE
Better javac docs

### ISSUE THREAD

**Issue by jlesquembre** [redstarssystems/pbuilder#1]
Thanks for pbuilder, it is a useful project!

I think there is an issue on the readme example when running the `javac` command:

the example uses `:java-source-paths "java-src"`, but I think it should be `:java-src-folder`. Also, the option `:target-folder` is not mentioned on the readme:

https://github.com/redstarssystems/pbuilder/blob/b21a2cf80872eb03cab34e4d0160abe1ca7dcb9d/src/org/rssys/pbuilder/process.clj#L119-L131

I also notice that `:target-folder` must be declared, or the default output folder is `/classes`. And that `/classes` is always appended to the target folder.

One last thing, I think for the javac command it would be useful to have a verbose option, to be able to debug if the java files where found or not.

**Comment by mikeananev** [comment]
Hello!
Thanks for issue.

I put :java-source-paths cause Leiningen uses this flag. Using the same flags in pbuilder makes it intuitive to use for Leiningen users.
:target-folder is present in readme example. I'll make default value "target" on 114 line of process.clj in a next release. Also I'll think about verbose option.

Thanks!

Mike.

**Comment by mikeananev** [comment]
Fixed in 0.1.10 version

**Comment by jlesquembre** [comment]
Thanks!
