### ISSUE TITLE
tools.deps api changes

### ISSUE THREAD

**Issue by puredanger** [redstarssystems/pbuilder#3]
Just wanted to drop a note that the newest version of tools.deps.alpha contains some api changes (moving towards getting out of alpha). So when you bump to tools.deps.alpha >= 0.9.745, you'll need to change your use of clojure.tools.deps.alpha.reader/slurp-deps - that is now in clojure.tools.deps.alpha.

**Comment by mikeananev** [comment]
Fixed with 0.2.2 version.
